//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> ReservationStartDate { get; set; }
        public Nullable<System.DateTime> ReservationEndDate { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
